---
# file: roles/frontend-buildserver/tasks

- name: register Chris Lea apt key
  apt_key: url=http://keyserver.ubuntu.com:11371/pks/lookup?search=0x136221EE520DDFAF0A905689B9316A7BC7917B12&op=get state=present
  sudo: yes

- name: register Chris Lea repo for nodejs
  apt_repository: repo='deb http://ppa.launchpad.net/chris-lea/node.js/ubuntu precise main' state=present
  sudo: yes

- name: install nodejs
  apt: pkg=nodejs update_cache=yes state=present
  sudo: yes

- name: install jdk for closure compiler
  apt: pkg=openjdk-7-jdk state=present
  sudo: yes

- name: download closure compiler
  get_url: url=https://closure-compiler.googlecode.com/files/compiler-20130823.tar.gz dest=/var/tmp/compiler-20130823.tar.gz

- name: make closure compiler directory
  command: mkdir -p /opt/closure-compiler/build creates=/opt/closure-compiler/build
  sudo: yes

- name: set permissions of closure compiler directory
  file: path=/opt/closure-compiler/build owner={{ owner }} state=directory
  sudo: yes

- name: install closure compiler
  command: tar xf /var/tmp/compiler-20130823.tar.gz chdir=/opt/closure-compiler/build creates=/opt/closure-compiler/build/closure-compiler.jar

- name: install frontend requirements based on package.json
  npm: path=/opt/mws/mongo-web-shell

- name: install grunt-cli
  npm: name=grunt-cli global=yes
  sudo: yes
